#
# Module manifest for module 'MSGraph'
#
# Generated by: mhickey
#
# Generated on: 6/30/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MSGraph.psm1'

# Version number of this module.
ModuleVersion = '3.5.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f4d5c866-265b-4da6-ab2a-ce5df3d14b40'

# Author of this module
Author = 'mhickey'

# Company or vendor of this module
CompanyName = 'Microsoft'

# Copyright statement for this module
Copyright = '(c) 2018 mhickey. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DISCLAIMER

    THIS CODE IS SAMPLE CODE. THESE SAMPLES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.
    MICROSOFT FURTHER DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES
    OF MERCHANTABILITY OR OF FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK ARISING OUT OF THE USE OR
    PERFORMANCE OF THE SAMPLES REMAINS WITH YOU. IN NO EVENT SHALL MICROSOFT OR ITS SUPPLIERS BE LIABLE FOR
    ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
    INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR
    INABILITY TO USE THE SAMPLES, EVEN IF MICROSOFT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR
    INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('AzureADAccessToken.Standard')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'ConditionalAccess.format.ps1xml', 'MSGraph.format.ps1xml', 
               'MSPIM.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Beta\SKUs.psm1', 
               'Beta\Applications\buildCredList.psm1', 
               'Beta\Applications\Get-MSGApplication.psm1', 
               'Beta\Applications\Get-MSGApplicationAssignedPolicy.psm1', 
               'Beta\Applications\Get-MSGApplicationCredential.psm1', 
               'Beta\Applications\Get-MSGApplicationExpiredStatus.psm1', 
               'Beta\Applications\Get-MSGApplicationExtensionProperty.psm1', 
               'Beta\Applications\Get-MSGApplicationKeyCredential.psm1', 
               'Beta\Applications\Get-MSGApplicationOwner.psm1', 
               'Beta\Applications\Get-MSGApplicationPasswordCredential.psm1', 
               'Beta\Applications\Get-MSGApplicationPermission.psm1', 
               'Beta\Applications\Get-MSGServicePrincipal.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalAppRoleAssignedTo.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalAppRoleAssignment.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalCreatedObject.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalCredential.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalKeyCredential.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalMembership.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalOAuth2PermissionGrant.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalOwnedObject.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalOwner.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalPasswordCredential.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalPolicy.psm1', 
               'Beta\Applications\Get-MSGServicePrincipalSingleSignOnCredential.psm1', 
               'Beta\Applications\New-MSGServiceAppRoleAssignment.psm1', 
               'Beta\Applications\New-MSGServicePrincipalOAuth2PermissionGrant.psm1', 
               'Beta\Applications\New-MSGServicePrincipalOwner.psm1', 
               'Beta\Applications\Remove-MSGApplicationKeyCredential.psm1', 
               'Beta\Applications\Remove-MSGApplicationPasswordCredential.psm1', 
               'Beta\Applications\Remove-MSGServiceAppRoleAssignment.psm1', 
               'Beta\Applications\Remove-MSGServicePrincipal.psm1', 
               'Beta\Applications\Remove-MSGServicePrincipalKeyCredential.psm1', 
               'Beta\Applications\Remove-MSGServicePrincipalOAuth2PermissionGrant.psm1', 
               'Beta\Applications\Remove-MSGServicePrincipalOwner.psm1', 
               'Beta\Applications\Remove-MSGServicePrincipalPasswordCredential.psm1', 
               'Beta\Applications\Set-MSGServicePrincipal.psm1', 
               'Beta\CloudPrint\Get-MSGPrintConnector.psm1', 
               'Beta\ConditionalAccess\Get-MSGConditionalAccessNamedLocation.psm1', 
               'Beta\ConditionalAccess\Get-MSGConditionalAccessPolicy.psm1', 
               'Beta\ConditionalAccess\New-MSGConditionalAccessPolicy.psm1', 
               'Beta\ConditionalAccess\Remove-MSGConditionalAccessPolicy.psm1', 
               'Beta\Devices\Add-MSGDeviceRegisteredOwner.psm1', 
               'Beta\Devices\Add-MSGDeviceRegisteredUser.psm1', 
               'Beta\Devices\Disable-MSGDevice.psm1', 
               'Beta\Devices\Enable-MSGDevice.psm1', 
               'Beta\Devices\Get-MSGDevice.psm1', 
               'Beta\Devices\Get-MSGDeviceRegisteredOwner.psm1', 
               'Beta\Devices\Get-MSGDeviceRegisteredUser.psm1', 
               'Beta\Directory\Get-MSGAdministrativeUnit.psm1', 
               'Beta\Directory\Get-MSGAdministrativeUnitMember.psm1', 
               'Beta\Directory\Get-MSGDeletedItem.psm1', 
               'Beta\Directory\Get-MSGDirectoryRole.psm1', 
               'Beta\Directory\Get-MSGDirectoryRoleMember.psm1', 
               'Beta\Directory\Get-MSGDirectoryRoleTemplate.psm1', 
               'Beta\Directory\Get-MSGDirectorySetting.psm1', 
               'Beta\Directory\Get-MSGDirectorySettingsTemplate.psm1', 
               'Beta\Directory\Get-MSGDomain.psm1', 
               'Beta\Directory\Get-MSGOAuth2PermissionGrant.psm1', 
               'Beta\Directory\Get-MSGOrganization.psm1', 
               'Beta\Directory\Get-MSGOrganizationContact.psm1', 
               'Beta\Directory\Get-MSGSchemaExtension.psm1', 
               'Beta\Directory\New-MSGOAuth2PermissionGrant.psm1', 
               'Beta\Directory\Remove-MSGDomain.psm1', 
               'Beta\Directory\Remove-MSGOAuth2PermissionGrant.psm1', 
               'Beta\Directory\Restore-MSGDeletedItem.psm1', 
               'Beta\Groups\Add-MSGGroupMember.psm1', 
               'Beta\Groups\Add-MSGGroupOwner.psm1', 
               'Beta\Groups\Get-MSGGroup.psm1', 
               'Beta\Groups\Get-MSGGroupAppAssignment.psm1', 
               'Beta\Groups\Get-MSGGroupMember.psm1', 
               'Beta\Groups\Get-MSGGroupMemberOf.psm1', 
               'Beta\Groups\Get-MSGGroupOwner.psm1', 
               'Beta\Groups\New-MSGGroup.psm1', 
               'Beta\Groups\ProcessGroupSearchString.psm1', 
               'Beta\Groups\Remove-MSGGroup.psm1', 
               'Beta\Groups\Remove-MSGGroupMember.psm1', 
               'Beta\Groups\Remove-MSGGroupOwner.psm1', 
               'Beta\IdentityProtection\Get-MSGRiskDetection.psm1', 
               'Beta\IdentityProtection\Get-MSGRiskyUser.psm1', 
               'Beta\IdentityProtection\Remove-MSGRiskyUser.psm1', 
               'Beta\PIM\Get-MSPIMAuditEvent.psm1', 
               'Beta\PIM\ResolveIDs.psm1', 
               'Beta\PIM\Directory\Disable-MSPIMDirectoryRoleAssignment.psm1', 
               'Beta\PIM\Directory\Enable-MSPIMDirectoryRoleAssignment.psm1', 
               'Beta\PIM\Directory\Get-MSPIMDirectoryRole.psm1', 
               'Beta\PIM\Directory\Get-MSPIMDirectoryRoleAssignment.psm1', 
               'Beta\PIM\Directory\Get-MSPIMDirectoryRoleAssignmentRequest.psm1', 
               'Beta\PIM\Directory\Get-MSPIMDirectoryRoleSetting.psm1', 
               'Beta\PIM\Directory\New-MSPIMDirectoryRoleAssignment.psm1', 
               'Beta\PIM\Directory\New-RoleMapping.psm1', 
               'Beta\PIM\Directory\Remove-MSPIMDirectoryRoleAssignment.psm1', 
               'Beta\PIM\Group\Get-MSPIMGroup.psm1', 
               'Beta\PIM\Group\Get-MSPIMGroupRoleAssignment.psm1', 
               'Beta\PIM\Resource\Get-MSPIMResource.psm1', 
               'Beta\PIM\Resource\Get-MSPIMResourceRoleAssignment.psm1', 
               'Beta\PIM\Resource\Get-MSPIMResourceRoleAssignmentRequest.psm1', 
               'Beta\PIM\Resource\Get-MSPIMResourceRoleDefinition.psm1', 
               'Beta\PIM\Resource\New-MSPIMResourceRoleAssignment.psm1', 
               'Beta\PIM\Resource\Remove-MSPIMResourceRoleAssignment.psm1', 
               'Beta\Policies\Get-MSGFeatureRolloutPolicy.psm1', 
               'Beta\Policies\Get-MSGPolicy.psm1', 
               'Beta\Policies\Get-MSGPolicyAppliesTo.psm1', 
               'Beta\Reports\Get-MSGApplicationSignInDetailedSummary.psm1', 
               'Beta\Reports\Get-MSGApplicationSignInSummary.psm1', 
               'Beta\Reports\Get-MSGAuditLogDirectoryEntry.psm1', 
               'Beta\Reports\Get-MSGProvisioningEntry.psm1', 
               'Beta\Reports\Get-MSGSecurityAlert.psm1', 
               'Beta\Reports\Get-MSGSignInLogEntry.psm1', 
               'Beta\Reports\New-ReportRecord.psm1', 
               'Beta\Reports\New-SigninRecord.psm1', 
               'Beta\Users\Get-MSGUser.psm1', 
               'Beta\Users\Get-MSGUserAppRoleAssignment.psm1', 
               'Beta\Users\Get-MSGUserCreatedObject.psm1', 
               'Beta\Users\Get-MSGUserDirectReport.psm1', 
               'Beta\Users\Get-MSGUserGroupMembership.psm1', 
               'Beta\Users\Get-MSGUserIsMemberOf.psm1', 
               'Beta\Users\Get-MSGUserJoinedTeam.psm1', 
               'Beta\Users\Get-MSGUserLastSigninActivity.psm1', 
               'Beta\Users\Get-MSGUserLicenseDetail.psm1', 
               'Beta\Users\Get-MSGUserManager.psm1', 
               'Beta\Users\Get-MSGUserMembership.psm1', 
               'Beta\Users\Get-MSGUserOAuthPermissionGrant.psm1', 
               'Beta\Users\Get-MSGUserOwnedDevics.psm1', 
               'Beta\Users\Get-MSGUserOwnedObject.psm1', 
               'Beta\Users\Get-MSGUserRegisteredDevice.psm1', 
               'Beta\Users\Get-MSGUserScopedRoleMembership.psm1', 
               'Beta\Users\Get-MSGUserUsageRight.psm1', 
               'Beta\Users\New-MSGUserAppRoleAssignment.psm1', 
               'Beta\Users\Remove-MSGUser.psm1', 
               'Beta\Users\Remove-MSGUserAppRoleAssignment.psm1', 
               'Beta\Users\Revoke-MSGUserAllRefreshToken.psm1', 
               'Beta\Users\Revoke-MSGUserSignInSession.psm1', 
               'Beta\Users\Set-MSGUser.psm1', 
               'Core\CoreGraph.psm1', 
               'Core\Invoke-SafeWebRequest.psm1', 
               'Utils\BuildUserANRSearchString.psm1', 
               'Utils\camelCase.psm1', 
               'Utils\Clear-MSGConfig.psm1', 
               'Utils\Get-AppAuthenticationResult.psm1', 
               'Utils\Get-DelegatedAuthentication.psm1', 
               'Utils\Get-MSGConfig.psm1', 
               'Utils\Get-UserAuthenticationResult.psm1', 
               'Utils\New-DynamicParam.psm1', 
               'Utils\New-Error.psm1', 
               'Utils\ProcessBoundParams.psm1', 
               'Utils\Set-MSGConfig.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MSGDeviceRegisteredOwner', 'Add-MSGDeviceRegisteredUser', 
               'Add-MSGGroupMember', 'Add-MSGGroupOwner', 'buildCredList', 
               'BuildPermissionTable', 'BuildUserANRSearchString', 'camelCase', 
               'Clear-MSGConfig', 'Connect-MSG', 'Disable-MSGDevice', 
               'Disable-MSPIMDirectoryRoleAssignment', 'Enable-MSGDevice', 
               'Enable-MSPIMDirectoryRoleAssignment', 
               'Get-AppAuthenticationResult', 'GetAppConsentedPermissions', 
               'GetApplicationAssignmentList', 'GetConsentedPermissions', 
               'GetCredentialExpiration', 'Get-DelegatedAuthentication', 
               'Get-MSGAdministrativeUnit', 'Get-MSGAdministrativeUnitMember', 
               'Get-MSGApplication', 'Get-MSGApplicationAssignedPolicy', 
               'Get-MSGApplicationCredential', 'Get-MSGApplicationExpiredStatus', 
               'Get-MSGApplicationExtensionProperty', 
               'Get-MSGApplicationKeyCredential', 'Get-MSGApplicationOwner', 
               'Get-MSGApplicationPasswordCredential', 
               'Get-MSGApplicationPermission', 
               'Get-MSGApplicationSignInDetailedSummary', 
               'Get-MSGApplicationSignInSummary', 'Get-MSGAuditLogDirectoryEntry', 
               'Get-MSGConditionalAccessNamedLocation', 
               'Get-MSGConditionalAccessPolicy', 'Get-MSGConfig', 
               'Get-MSGCurrentSession', 'Get-MSGDeletedItem', 'Get-MSGDevice', 
               'Get-MSGDeviceRegisteredOwner', 'Get-MSGDeviceRegisteredUser', 
               'Get-MSGDirectoryRole', 'Get-MSGDirectoryRoleMember', 
               'Get-MSGDirectoryRoleTemplate', 'Get-MSGDirectorySetting', 
               'Get-MSGDirectorySettingsTemplate', 'Get-MSGDomain', 
               'Get-MSGEnvironmentList', 'Get-MSGFeatureRolloutPolicy', 
               'Get-MSGGroup', 'Get-MSGGroupAppAssignment', 'Get-MSGGroupMember', 
               'Get-MSGGroupMemberOf', 'Get-MSGGroupOwner', 'Get-MSGLinkedObject', 
               'Get-MSGOAuth2PermissionGrant', 'Get-MSGObject', 'Get-MSGObjectById', 
               'Get-MSGOrganization', 'Get-MSGOrganizationContact', 'Get-MSGPolicy', 
               'Get-MSGPolicyAppliesTo', 'Get-MSGPrintConnector', 'Get-MSGProfile', 
               'Get-MSGProvisioningEntry', 'Get-MSGRiskDetection', 
               'Get-MSGRiskyUser', 'Get-MSGSchemaExtension', 'Get-MSGSecurityAlert', 
               'Get-MSGServicePrincipal', 
               'Get-MSGServicePrincipalAppRoleAssignedTo', 
               'Get-MSGServicePrincipalAppRoleAssignment', 
               'Get-MSGServicePrincipalCreatedObject', 
               'Get-MSGServicePrincipalCredential', 
               'Get-MSGServicePrincipalKeyCredential', 
               'Get-MSGServicePrincipalMembership', 
               'Get-MSGServicePrincipalOAuth2PermissionGrant', 
               'Get-MSGServicePrincipalOwnedObject', 
               'Get-MSGServicePrincipalOwner', 
               'Get-MSGServicePrincipalPasswordCredential', 
               'Get-MSGServicePrincipalPolicy', 
               'Get-MSGServicePrincipalSingleSignOnCredential', 
               'Get-MSGSignInLogEntry', 'Get-MSGSubscribedSKUs', 'Get-MSGUser', 
               'Get-MSGUserAppRoleAssignment', 'Get-MSGUserCreatedObject', 
               'Get-MSGUserDirectReport', 'Get-MSGUserGroupMembership', 
               'Get-MSGUserIsMemberOf', 'Get-MSGUserJoinedTeam', 
               'Get-MSGUserLastSigninActivity', 'Get-MSGUserLicenseDetail', 
               'Get-MSGUserManager', 'Get-MSGUserMembership', 
               'Get-MSGUserOAuthPermissionGrant', 'Get-MSGUserOwnedDevice', 
               'Get-MSGUserOwnedObject', 'Get-MSGUserRegisteredDevice', 
               'Get-MSGUserScopedRoleMembership', 'Get-MSGUserUsageRight', 
               'Get-MSPIMAuditEvent', 'Get-MSPIMDirectoryRole', 
               'Get-MSPIMDirectoryRoleAssignment', 
               'Get-MSPIMDirectoryRoleAssignmentRequest', 
               'Get-MSPIMDirectoryRoleSetting', 'Get-MSPIMGroup', 
               'Get-MSPIMGroupRoleAssignment', 'Get-MSPIMResource', 
               'Get-MSPIMResourceRoleAssignment', 
               'Get-MSPIMResourceRoleAssignmentRequest', 
               'Get-MSPIMResourceRoleDefinition', 'GetOwnerList', 
               'GetPermissionList', 'GetPermissionName', 'GetResourceName', 
               'Get-UserAuthenticationResult', 'Invoke-SafeWebRequest', 
               'New-DynamicParam', 'New-Error', 'New-MSGConditionalAccessPolicy', 
               'New-MSGGroup', 'New-MSGOAuth2PermissionGrant', 'New-MSGObject', 
               'New-MSGServiceAppRoleAssignment', 
               'New-MSGServicePrincipalOAuth2PermissionGrant', 
               'New-MSGServicePrincipalOwner', 'New-MSGUserAppRoleAssignment', 
               'New-MSPIMDirectoryRoleAssignment', 
               'New-MSPIMResourceRoleAssignment', 'New-ReportRecord', 
               'New-RoleMapping', 'New-SigninRecord', 'ProcessBoundParams', 
               'ProcessCoreBoundParams', 'ProcessCredentials', 
               'ProcessGroupSearchString', 'Remove-MSGApplicationKeyCredential', 
               'Remove-MSGApplicationPasswordCredential', 
               'Remove-MSGConditionalAccessPolicy', 'Remove-MSGDomain', 
               'Remove-MSGGroup', 'Remove-MSGGroupMember', 'Remove-MSGGroupOwner', 
               'Remove-MSGOAuth2PermissionGrant', 'Remove-MSGObject', 
               'Remove-MSGRiskyUser', 'Remove-MSGServiceAppRoleAssignment', 
               'Remove-MSGServicePrincipal', 
               'Remove-MSGServicePrincipalKeyCredential', 
               'Remove-MSGServicePrincipalOAuth2PermissionGrant', 
               'Remove-MSGServicePrincipalOwner', 
               'Remove-MSGServicePrincipalPasswordCredential', 'Remove-MSGUser', 
               'Remove-MSGUserAppRoleAssignment', 
               'Remove-MSPIMDirectoryRoleAssignment', 
               'Remove-MSPIMResourceRoleAssignment', 'ResolveIds', 
               'Restore-MSGDeletedItem', 'Revoke-MSGUserAllRefreshToken', 
               'Revoke-MSGUserSignInSession', 'SetAuthHeader', 'Set-MSGConfig', 
               'Set-MSGObject', 'Set-MSGProfile', 'Set-MSGServicePrincipal', 
               'Set-MSGUser', 'UpdateTypes'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Add-MSGgraphGroupOwner', 'Check-MSGGroupMembership', 
               'Disconnect-MSG', 'Get-MSGGroupMembership', 'Get-MSGUserMembership', 
               'Remove-MSGraphApplicationKeyCredential', 'Set-MSGraphUser'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Auto-generated by Refresh-Manifest on 06-30-2023_04.41_PM'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

